app:
  replicas: 1

  command: ["--max-memory", "3", "serve"]

  # Staging environment specific environment vars
  environment: {}

  scheduling:
    preferSpotInstances: true

  # Other pods in the same node might suffer when otp-server is starting
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 250m
      memory: 2Gi
