app:
  replicas: 1

  # Staging environment specific environment vars
  environment: {}

  scheduling:
    preferSpotInstances: true

  # Other pods in the same node might suffer when otp-server is starting
  resources:
    limits:
      memory: 14Gi
    requests:
      cpu: 1000m
      memory: 12Gi
