app:
  replicas: 1

  # Production environment specific environment vars
  environment: {}

  # Other pods in the same node might suffer when otp-server is starting
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

  nodeSelector:
    shotl.com/workload-type: memory-intensive

  tolerations:
    - key: shotl.com/workload-type
      operator: Equal
      value: memory-intensive
      effect: NoSchedule
